version: '3.8'
services:
  eureka-server:
    build: ./DiscoveryService
    ports:
      - "8761:8761"

  api-gateway:
    build: ./ApiGateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  forum-service:
    build: ./ForumService
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server