server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: forum-service
          uri: lb://forum-service
          predicates:
            - Path=/foro/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comentarios/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka